package com.goJek.exception;


/**
 * This class is used to throw checked exceptions to client generated by the application.
 *
 * Use cases:
 *   - invalid commands
 *   - invalid actions (eg. leave an empty slot etc)
 *
 * */
public class ParkingException extends Exception {
    public ParkingException(String errorMessage) {
        super(errorMessage);
    }
}
